FROM php:8.3-fpm

WORKDIR /app

RUN apt-get update && apt-get install -y \
    git unzip libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY {{ service.dir }}/composer.json {{ service.dir }}/composer.lock* ./
RUN composer install --no-scripts --no-autoloader

COPY {{ service.dir }}/ .
RUN composer dump-autoload --optimize

CMD ["php-fpm"]
